"""empty message

Revision ID: 171e17127b07
Revises: f31392574c4d
Create Date: 2020-08-08 21:21:43.212440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "171e17127b07"
down_revision = "f31392574c4d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blacklist_tokens",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=500), nullable=False),
        sa.Column("blacklisted_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.add_column("Users", sa.Column("admin", sa.Boolean(), nullable=False))
    op.add_column("Users", sa.Column("email", sa.String(length=255), nullable=False))
    op.add_column("Users", sa.Column("password", sa.String(length=255), nullable=False))
    op.add_column("Users", sa.Column("registered_on", sa.DateTime(), nullable=False))
    op.add_column("Users", sa.Column("team", sa.String(length=128), nullable=True))
    op.alter_column(
        "Users", "name", existing_type=mysql.VARCHAR(length=100), nullable=False
    )
    op.create_unique_constraint(None, "Users", ["email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "Users", type_="unique")
    op.alter_column(
        "Users", "name", existing_type=mysql.VARCHAR(length=100), nullable=True
    )
    op.drop_column("Users", "team")
    op.drop_column("Users", "registered_on")
    op.drop_column("Users", "password")
    op.drop_column("Users", "email")
    op.drop_column("Users", "admin")
    op.drop_table("blacklist_tokens")
    # ### end Alembic commands ###
