"""empty message

Revision ID: dcf72e579f09
Revises: 
Create Date: 2020-09-12 15:50:57.396683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf72e579f09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Equipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('Colaboradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('equipe_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['equipe_id'], ['Equipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=True),
    sa.Column('matricula', sa.Integer(), nullable=True),
    sa.Column('equipe_id', sa.Integer(), nullable=True),
    sa.Column('colaborador_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['colaborador_id'], ['Colaboradores.id'], ),
    sa.ForeignKeyConstraint(['equipe_id'], ['Equipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Doacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doacao', sa.String(length=120), nullable=True),
    sa.Column('tipo', sa.String(length=120), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('colaborador_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('pontuacao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['Alunos.id'], ),
    sa.ForeignKeyConstraint(['colaborador_id'], ['Colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Doacoes')
    op.drop_table('Alunos')
    op.drop_table('Colaboradores')
    op.drop_table('blacklist_tokens')
    op.drop_table('Equipes')
    # ### end Alembic commands ###
