"""empty message

Revision ID: a3c281f75f20
Revises: 051714ca5cc3
Create Date: 2020-10-20 15:13:28.660184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3c281f75f20'
down_revision = '051714ca5cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Equipes', sa.Column('sigla', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Equipes', 'sigla')
    # ### end Alembic commands ###
